export default {
  easy: [
    {
      x: 9,
      y: 6,
      words: [
        {
          word: 1,
          text: "lapiseiras",
          y: "2",
          x: "1-9",
          horizontal: true,
          tip: { x: 1, y: 1, value: "Objeto de escrita que é recarregável" },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
          doubles: [5],
        },
        {
          word: 2,
          text: "aparar",
          y: "1-6",
          x: "3",
          vertical: true,
          tip: { x: 2, y: 1, value: "Cortar a Grama" },
        },
        {
          word: 3,
          text: "adubo",
          y: "2-6",
          x: "2",
          vertical: true,
          tip: { x: 2, y: 1, value: "Fertilizante de Solo" },
        },
        {
          word: 4,
          text: "asetral",
          y: "1-6",
          x: "5",
          vertical: true,
          tip: { x: 4, y: 1, value: "De baixo (?): Triste" },
          doubles: [2],
        },
        {
          word: 5,
          text: "bis",
          y: "1-3",
          x: "7",
          vertical: true,
          tip: { x: 6, y: 1, value: "Pedido de repetição ao bom músico" },
        },
        {
          word: 6,
          text: "rondar",
          y: "2-6",
          x: "8",
          vertical: true,
          tip: { x: 8, y: 1, value: "Inspeção policial" },
        },
        {
          word: 7,
          text: "cantar",
          y: "1-6",
          x: "9",
          vertical: true,
          tip: { x: 8, y: 1, value: "Entoar Músicas" },
        },
        {
          word: 8,
          text: "aurora",
          y: "4",
          x: "1-6",
          horizontal: true,
          tip: { x: 1, y: 3, value: "Claridade antes do sol nascer" },
        },
        {
          word: 9,
          text: "od",
          y: "4-5",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 3, value: "Olívio Dutra, político brasileiro" },
        },
        {
          word: 10,
          text: "son",
          y: "3",
          x: "7-9",
          horizontal: true,
          tip: { x: 6, y: 3, value: "Filho em inglês" },
        },
        {
          word: 11,
          text: "ala",
          y: "4-6",
          x: "6",
          vertical: true,
          tip: {
            x: 6,
            y: 3,
            value: "Palavra utilizada no árabe para designar Deus",
          },
        },
        {
          word: 12,
          text: "av",
          y: "5-6",
          x: "7",
          vertical: true,
          tip: { x: 7, y: 4, value: "Ângela Vieira, Atriz" },
        },
        {
          word: 13,
          text: "badalada",
          y: "5",
          x: "2-9",
          horizontal: true,
          tip: { x: 1, y: 5, value: "Som do Sino" },
        },
        {
          word: 14,
          text: "cor",
          y: "6",
          x: "1-3",
          horizontal: true,
          tip: { x: 1, y: 5, value: "Divisão do arco-íris" },
        },
        {
          word: 15,
          text: "lavar",
          y: "6",
          x: "5-9",
          horizontal: true,
          tip: { x: 4, y: 6, value: "Banhar com água" },
        },
      ],
    },
  ],
  medium: [
    {
      x: 14,
      y: 9,
      words: [
        {
          word: 1,
          text: "carrodecorrida",
          y: "2",
          x: "1-14",
          horizontal: true,
          tip: { x: 1, y: 1, value: "Automóvel usado na fórmula 1." },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
        },
        {
          word: 2,
          text: "nos",
          y: "3",
          x: "5-6",
          horizontal: true,
          tip: { x: 4, y: 3, value: "Eu e eles." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
          doubles: [6],
        },
        {
          word: 3,
          text: "u",
          y: "3",
          x: "8",
          horizontal: true,
          tip: { x: 7, y: 3, value: "Quinta vogal" },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 4,
          text: "arco",
          y: "3",
          x: "10-13",
          horizontal: true,
          tip: { x: 9, y: 3, value: "Arma indígena." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 5,
          text: "guindastes",
          y: "4",
          x: "1-10",
          horizontal: true,
          tip: { x: 1, y: 3, value: "Aparelho que ergue grandes pesos (pl.)." },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
        },
        {
          word: 6,
          text: "in",
          y: "5",
          x: "2-3",
          horizontal: true,
          tip: { x: 1, y: 5, value: "Na moda (gíria)." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 7,
          text: "air",
          y: "5",
          x: "7-9",
          horizontal: true,
          tip: { x: 6, y: 5, value: "Ar, em inglês." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 8,
          text: "sais",
          y: "5",
          x: "11-14",
          horizontal: true,
          tip: { x: 10, y: 5, value: "Cristais de banho." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 9,
          text: "zezedicamargo",
          y: "6",
          x: "2-14",
          horizontal: true,
          tip: { x: 1, y: 6, value: "Parceiro de Luciano (MPB)" },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 10,
          text: "raios",
          y: "7",
          x: "1-5",
          horizontal: true,
          tip: { x: 1, y: 6, value: "Antecedem os trovões." },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
        },
        {
          word: 11,
          text: "ela",
          y: "7",
          x: "10-12",
          horizontal: true,
          tip: { x: 9, y: 7, value: "Inscrição no banheiro feminino." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 12,
          text: "dr",
          y: "8",
          x: "2-3",
          horizontal: true,
          tip: { x: 1, y: 8, value: "Doutor (abrev.)." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 13,
          text: "atlas",
          y: "8",
          x: "6-10",
          horizontal: true,
          tip: { x: 5, y: 8, value: "Livro com coleção de mapas." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 14,
          text: "doo",
          y: "8",
          x: "12-14",
          horizontal: true,
          tip: { x: 11, y: 8, value: "Scooby - (?), cão de desenho animado." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 15,
          text: "boasnovas",
          y: "9",
          x: "1-8",
          horizontal: true,
          tip: { x: 1, y: 8, value: "Notícias agradáveis." },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
          doubles: [8],
        },
        {
          word: 16,
          text: "abater",
          y: "9",
          x: "10-14",
          horizontal: true,
          tip: { x: 9, y: 9, value: "Dar desconto (no preço)." },
          arrow: { icon: "to-right", pos: { y: "45%", x: "5%" }, size: 10 },
        },
        {
          word: 17,
          text: "ajuizado",
          y: "2-9",
          x: "2",
          vertical: true,
          tip: { x: 2, y: 1, value: "Prudente." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 18,
          text: "jardineira",
          y: "1-9",
          x: "3",
          vertical: true,
          tip: { x: 2, y: 1, value: "Local onde se colocam plantas." },
          arrow: { icon: "left-to-bottom", pos: { x: "-2%", y: "8%" } },
          doubles: [1],
        },
        {
          word: 19,
          text: "r",
          y: "2",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 1, value: "Rua (abrev.)." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 20,
          text: "n",
          y: "4",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 3, value: "Ene." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 21,
          text: "zo",
          y: "6-7",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 5, value: "Sílabas de zona." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 22,
          text: "s",
          y: "9",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 8, value: "Formato de estada sinuosa." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 23,
          text: "londres",
          y: "1-7",
          x: "5",
          vertical: true,
          tip: { x: 4, y: 1, value: "Capital da inglaterra." },
          arrow: { icon: "left-to-bottom", pos: { x: "-2%", y: "8%" } },
        },
        {
          word: 24,
          text: "idosa",
          y: "1-4",
          x: "6",
          vertical: true,
          tip: { x: 7, y: 1, value: "A mulher da terceira idade." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
          doubles: [3],
        },
        {
          word: 25,
          text: "ao",
          y: "8-9",
          x: "6",
          vertical: true,
          tip: { x: 6, y: 7, value: "Vogais de 'gato'." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 26,
          text: "sai",
          y: "4-6",
          x: "7",
          vertical: true,
          tip: { x: 7, y: 3, value: "Afasta-se." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 27,
          text: "tv",
          y: "8-9",
          x: "7",
          vertical: true,
          tip: { x: 7, y: 7, value: "Televisão (abrev.)." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 28,
          text: "cuticulas",
          y: "2-9",
          x: "8",
          vertical: true,
          tip: { x: 8, y: 1, value: "Peles removidas pela manicure." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
          doubles: [9],
        },
        {
          word: 29,
          text: "era",
          y: "4-6",
          x: "9",
          vertical: true,
          tip: { x: 9, y: 3, value: "Época período." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 30,
          text: "peras",
          y: "1-4",
          x: "10",
          vertical: true,
          tip: { x: 9, y: 1, value: "Fruta de polpa branca (pl.)." },
          arrow: { icon: "left-to-bottom", pos: { x: "-2%", y: "8%" } },
          doubles: [1],
        },
        {
          word: 31,
          text: "mesa",
          y: "6-9",
          x: "10",
          vertical: true,
          tip: { x: 10, y: 5, value: "Móvel de escritório." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 32,
          text: "sal",
          y: "5-7",
          x: "11",
          vertical: true,
          tip: { x: 11, y: 4, value: "Tempero iodado." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 33,
          text: "bicharada",
          y: "1-9",
          x: "12",
          vertical: true,
          tip: { x: 11, y: 1, value: "Grande número de animais." },
          arrow: { icon: "left-to-bottom", pos: { x: "-2%", y: "8%" } },
        },
        {
          word: 34,
          text: "ido",
          y: "1-3",
          x: "13",
          vertical: true,
          tip: { x: 14, y: 1, value: "Tempo passado." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 35,
          text: "ig",
          y: "5-6",
          x: "13",
          vertical: true,
          tip: { x: 13, y: 4, value: "Igrid Guimarães atriz." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
        {
          word: 36,
          text: "ote",
          y: "8-9",
          x: "13",
          vertical: true,
          tip: { x: 13, y: 7, value: "Sufixo de 'filhote'." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
          doubles: [9],
        },
        {
          word: 37,
          text: "isopor",
          y: "4-9",
          x: "14",
          vertical: true,
          tip: { x: 14, y: 3, value: "Utensílio do vendedor de praia." },
          arrow: { icon: "to-bottom", pos: { x: "45%", y: "5%" }, size: 7.5 },
        },
      ],
      data: [
        [
          { tips: [1] },
          { tips: [17, 18] },
          {
            double: true,
            word: [18],
            arrow: { icon: "left-to-bottom", x: "-2%", y: "8%" },
          },
          { tips: [19, 23] },
          { word: [23], arrow: { icon: "left-to-bottom", x: "-2%", y: "8%" } },
          {
            word: [24],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { tips: [24] },
          { tips: [28] },
          { tips: [30] },
          {
            double: true,
            word: [30],
            arrow: { icon: "left-to-bottom", x: "-2%", y: "8%" },
          },
          { tips: [33] },
          { word: [33], arrow: { icon: "left-to-bottom", x: "-2%", y: "8%" } },
          {
            word: [34],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { tips: [34] },
        ],
        [
          { word: [1], arrow: { icon: "top-to-right", x: "6px", y: "0" } },
          {
            word: [1, 17],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [1, 18] },
          {
            word: [1, 19],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [1, 23] },
          { word: [1, 24] },
          { word: [1] },
          {
            word: [1, 28],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [1] },
          { word: [1, 30] },
          { word: [1] },
          { word: [1, 33] },
          { word: [1, 34] },
          { word: [1] },
        ],
        [
          { tips: [5] },
          { word: [17] },
          { word: [18] },
          { tips: [2, 20] },
          {
            word: [2, 23],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { double: true, word: [2, 24] },
          { tips: [3, 26] },
          {
            word: [3, 28],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { tips: [4, 29] },
          {
            word: [4, 30],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [4] },
          { word: [4, 33] },
          { word: [4, 34] },
          { tips: [37] },
        ],
        [
          { word: [5], arrow: { icon: "top-to-right", x: "6px", y: "0" } },
          { word: [5, 17] },
          { word: [5, 18] },
          {
            word: [5, 20],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [5, 23] },
          { word: [5, 24] },
          {
            word: [5, 26],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [5, 28] },
          {
            word: [5, 29],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [5, 30] },
          { tips: [32] },
          { word: [33] },
          { tips: [35] },
          {
            word: [37],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
        ],
        [
          { tips: [6] },
          {
            word: [6, 17],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [6, 18] },
          { tips: [21] },
          { word: [23] },
          { tips: [7] },
          {
            word: [7, 26],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [7, 28] },
          { word: [7, 29] },
          { tips: [8, 31] },
          {
            word: [8, 32],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [8, 33] },
          {
            word: [8, 35],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [8, 37] },
        ],
        [
          { tips: [9, 10] },
          {
            word: [9, 17],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [9, 18] },
          {
            word: [9, 21],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [9, 23] },
          { word: [9] },
          { word: [9, 26] },
          { word: [9, 28] },
          { word: [9, 29] },
          {
            word: [9, 31],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [9, 32] },
          { word: [9, 33] },
          { word: [9, 35] },
          { word: [9, 37] },
        ],
        [
          { word: [10], arrow: { icon: "top-to-right", x: "6px", y: "0" } },
          { word: [10, 17] },
          { word: [10, 18] },
          { word: [10, 21] },
          { word: [10, 23] },
          { tips: [25] },
          { tips: [27] },
          { word: [28] },
          { tips: [11] },
          {
            word: [11, 31],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [11, 32] },
          { word: [11, 33] },
          { tips: [36] },
          { word: [37] },
        ],
        [
          { tips: [12, 15] },
          {
            word: [12, 17],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [12, 18] },
          { tips: [22] },
          { tips: [13] },
          {
            word: [13, 25],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          {
            word: [13, 27],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [13, 28] },
          { word: [13] },
          { word: [13, 31] },
          { tips: [14] },
          {
            word: [14, 33],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          {
            word: [14, 36],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [14, 37] },
        ],
        [
          { word: [15], arrow: { icon: "top-to-right", x: "6px", y: "0" } },
          { word: [15, 17] },
          { word: [15, 18] },
          {
            word: [15, 22],
            arrow: { icon: "to-bottom", x: "45%", y: "5%", size: 7.5 },
          },
          { word: [15] },
          { word: [15, 25] },
          { word: [15, 27] },
          { double: true, word: [15, 28] },
          { tips: [16] },
          {
            word: [16, 31],
            arrow: { icon: "to-right", x: "5%", y: "45%", size: 10 },
          },
          { word: [16] },
          { word: [16, 33] },
          { word: [16, 36], double: true },
          { word: [16, 37] },
        ],
      ],
    },
  ],
};
