export default {
  easy: [
    {
      x: 9,
      y: 6,
      words: [
        {
          word: 1,
          text: "lapiseiras",
          y: "2",
          x: "1-9",
          horizontal: true,
          tip: { x: 1, y: 1, value: "Objeto de escrita que é recarregável" },
          arrow: { icon: "top-to-right", pos: { x: "6px", y: "0" } },
          doubles: [5],
        },
        {
          word: 2,
          text: "aparar",
          y: "1-6",
          x: "3",
          vertical: true,
          tip: { x: 2, y: 1, value: "Cortar a Grama" },
        },
        {
          word: 3,
          text: "adubo",
          y: "2-6",
          x: "2",
          vertical: true,
          tip: { x: 2, y: 1, value: "Fertilizante de Solo" },
        },
        {
          word: 4,
          text: "asetral",
          y: "1-6",
          x: "5",
          vertical: true,
          tip: { x: 4, y: 1, value: "De baixo (?): Triste" },
          doubles: [2],
        },
        {
          word: 5,
          text: "bis",
          y: "1-3",
          x: "7",
          vertical: true,
          tip: { x: 6, y: 1, value: "Pedido de repetição ao bom músico" },
        },
        {
          word: 6,
          text: "rondar",
          y: "2-6",
          x: "8",
          vertical: true,
          tip: { x: 8, y: 1, value: "Inspeção policial" },
        },
        {
          word: 7,
          text: "cantar",
          y: "1-6",
          x: "9",
          vertical: true,
          tip: { x: 8, y: 1, value: "Entoar Músicas" },
        },
        {
          word: 8,
          text: "aurora",
          y: "4",
          x: "1-6",
          horizontal: true,
          tip: { x: 1, y: 3, value: "Claridade antes do sol nascer" },
        },
        {
          word: 9,
          text: "od",
          y: "4-5",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 3, value: "Olívio Dutra, político brasileiro" },
        },
        {
          word: 10,
          text: "son",
          y: "3",
          x: "7-9",
          horizontal: true,
          tip: { x: 6, y: 3, value: "Filho em inglês" },
        },
        {
          word: 11,
          text: "ala",
          y: "4-6",
          x: "6",
          vertical: true,
          tip: {
            x: 6,
            y: 3,
            value: "Palavra utilizada no árabe para designar Deus",
          },
        },
        {
          word: 12,
          text: "av",
          y: "5-6",
          x: "7",
          vertical: true,
          tip: { x: 7, y: 4, value: "Ângela Vieira, Atriz" },
        },
        {
          word: 13,
          text: "badalada",
          y: "5",
          x: "2-9",
          horizontal: true,
          tip: { x: 1, y: 5, value: "Som do Sino" },
        },
        {
          word: 14,
          text: "cor",
          y: "6",
          x: "1-3",
          horizontal: true,
          tip: { x: 1, y: 5, value: "Divisão do arco-íris" },
        },
        {
          word: 15,
          text: "lavar",
          y: "6",
          x: "5-9",
          horizontal: true,
          tip: { x: 4, y: 6, value: "Banhar com água" },
        },
      ],
    },
  ],
};
