{
  hard: [
    {
      x: 14,
      y: 9,
      words: [
        {
          word: 1,
          text: "descalcificação",
          y: "2",
          x: "1-14",
          horizontal: true,
          tip: { x: 1, y: 1, value: "Processo associado à osteoporose" },
          arrow: {},
          doubles: [5],
        },
        {
          word: 2,
          text: "ator",
          y: "3",
          x: "4-7",
          horizontal: true,
          tip: { x: 3, y: 3, value: "Intérprete" },
          arrow: {},
        },
        {
          word: 3,
          text: "romã",
          y: "3",
          x: "9-12",
          horizontal: true,
          tip: { x: 8, y: 3, value: "Fruto ligado à fecundidade (Ant.)" },
          arrow: {},
        },
        {
          word: 4,
          text: "erratica",
          y: "2",
          x: "2-9",
          horizontal: true,
          tip: {
            x: 1,
            y: 4,
            value: "Composição de Caetano Veloso gravada por Gal Costa",
          },
          arrow: {},
        },
        {
          word: 5,
          text: "root",
          y: "4",
          x: "11-14",
          horizontal: true,
          tip: { x: 10, y: 4, value: "Raíz em inglês" },
          arrow: {},
        },
        {
          word: 6,
          text: "canon",
          y: "5",
          x: "1-4",
          horizontal: true,
          tip: { x: 1, y: 3, value: "Modelo religioso" },
          arrow: {},
          doubles: [1],
        },
        {
          word: 7,
          text: "ur",
          y: "5",
          x: "13-14",
          horizontal: true,
          tip: { x: 12, y: 5, value: "Pátria de Abraão (Bíblia)" },
          arrow: {},
        },
        {
          word: 8,
          text: "tia",
          y: "6",
          x: "2-4",
          horizontal: true,
          tip: { x: 1, y: 6, value: "(?) Ciata, matriarca do samba" },
          arrow: {},
        },
        {
          word: 9,
          text: "narrativa",
          y: "6",
          x: "6-14",
          horizontal: true,
          tip: {
            x: 5,
            y: 6,
            value:
              "Forma literária que privilegia a descrição de eventos reais e imaginários",
          },
          arrow: {},
        },
        {
          word: 10,
          text: "une",
          y: "7",
          x: "3-5",
          horizontal: true,
          tip: { x: 2, y: 7, value: "Entidade opositora do regime militar" },
          arrow: {},
        },
        {
          word: 11,
          text: "sit",
          y: "7",
          x: "12-14",
          horizontal: true,
          tip: { x: 11, y: 7, value: "Sentar em inglês" },
          arrow: {},
        },
        {
          word: 12,
          text: "arbitragem",
          y: "8",
          x: "2-11",
          horizontal: true,
          tip: { x: 1, y: 8, value: "Ativivade amadora ligada ao futebol" },
          arrow: {},
        },
        {
          word: 13,
          text: "alfa",
          y: "9",
          x: "1-4",
          horizontal: true,
          tip: {
            x: 1,
            y: 8,
            value: "Partícula (?), tipo de emissão radioativa",
          },
          arrow: {},
        },
        {
          word: 14,
          text: "ecleticos",
          y: "9",
          x: "6-14",
          horizontal: true,
          tip: { x: 5, y: 9, value: "Que apreciam músicas diversas" },
          arrow: {},
        },
        {
          word: 15,
          text: "eventual",
          y: "2-9",
          x: "2",
          vertical: true,
          tip: { x: 2, y: 1, value: "Casual; fortuito" },
          arrow: {},
        },
        {
          word: 16,
          text: "roi",
          y: "4-6",
          x: "3",
          vertical: true,
          tip: { x: 3, y: 3, value: "Alimenta-se como os ratos" },
          arrow: {},
        },
        {
          word: 17,
          text: "carnauba",
          y: "2-9",
          x: "4",
          vertical: true,
          tip: { x: 4, y: 1, value: "Árvore símbolo do Piauí" },
          arrow: {},
        },
        {
          word: 18,
          text: "malta",
          y: "1-4",
          x: "5",
          vertical: true,
          tip: { x: 4, y: 1, value: "País que integra a união europeia desse 2004" },
					arrow: {},
					doubles: [2]
				},
				{
          word: 19,
          text: "cotonete",
          y: "2-9",
          x: "6",
          vertical: true,
          tip: { x: 6, y: 1, value: "Haste flexível para limpeza de ouvido" },
					arrow: {}
				},
				{
          word: 20,
          text: "birita",
          y: "1-6",
          x: "7",
          vertical: true,
          tip: { x: 8, y: 1, value: "Cachaça (bras.)" },
					arrow: {}
				},
				{
          word: 21,
          text: "rc",
          y: "8-9",
          x: "7",
          vertical: true,
          tip: { x: 7, y: 7, value: "Ray  Conniff maestro dos EUA" },
					arrow: {}
				},
				{
          word: 21,
          text: "f",
          y: "2",
          x: "8",
          vertical: true,
          tip: { x: 8, y: 1, value: "Flúor (símbolo)" },
					arrow: {}
				},
				{
          word: 22,
          text: "real",
          y: "6-9",
          x: "8",
          vertical: true,
          tip: { x: 8, y: 1, value: "(?) Madrid, time de Kaká em 2012" },
					arrow: {}
				},
				{
          word: 23,
          text: "pira",
          y: "1-4",
          x: "9",
          vertical: true,
          tip: { x: 10, y: 1, value: "Um dos símbolos olímpicos" },
					arrow: {}
				},
				{
          word: 24,
          text: "ge",
          y: "8-9",
          x: "9",
          vertical: true,
          tip: { x: 9, y: 7, value: "Germânio (símbolo)" },
					arrow: {}
				},
				{
          word: 25,
          text: "manet",
          y: "5-9",
          x: "10",
          vertical: true,
					tip: { x: 9, y: 4, value: "Pintor francês de 'A Sacada'" },
					arrow: {}
				},
				{
          word: 26,
          text: "samret",
          y: "1-6",
          x: "11",
          vertical: true,
          tip: { x: 11, y: 7, value: "Balneário" },
					arrow: {}
				},
				{
          word: 27,
          text: "mi",
          y: "8-9",
          x: "11",
          vertical: true,
          tip: { x: 11, y: 7, value: "12ª letra grega" },
					arrow: {}
				},
				{
          word: 28,
          text: "ação",
          y: "1-4",
          x: "12",
          vertical: true,
          tip: { x: 13, y: 1, value: "Ato" },
					arrow: {}
				},
				{
          word: 29,
          text: "ouvido",
          y: "4-9",
          x: "13",
          vertical: true,
          tip: { x: 13, y: 3, value: "Fone de (?), acessório do walkman" },
					arrow: {}
				},
				{
          word: 30,
          text: "contratos",
          y: "1-9",
          x: "14",
          vertical: true,
          tip: { x: 13, y: 1, value: "Acordos com validade legal" },
					arrow: {}
				},
      ],
    },
  ];
}
